# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build & Deploy

on:
  push:
    branches: [ "development" ]
  #pull_request:
  #  branches: [ "development" ]

jobs:
  build:

    runs-on: angular

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build
      run: |
        npm install
        npm install -g @angular/cli
        npm run build
        npm run sonar-scanner

      env:
        SONAR_TOKEN: $${{development.SONAR_TOKEN}}
      
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_DEV_URL }}
        username: ${{ secrets.FTP_DEV_USERNAME }}
        password: ${{ secrets.FTP_DEV_PASSWORD }}
        # prtocall: ftps
        port: 2122
        local-dir: ./dist/
        server-dir: deploy/angular/
        timeout: 60000000
